// "singleton_instance_id": 1,
// "logo_1": null,
// "logo_2": null,
// "logo_text": "Официальный сайт врио губернатора Астраханской области Сергея Морозова",
// "vk_link": "https://paste_link/",
// "insta_link": "https://paste_link/",
// "fb_link": "https://paste_link/",
// "delivery_condition": "",
// "contacts": "",
// "page_type_cart": null,
// "page_type_account": null,
// "page_type_auth": null,
// "page_type_reg": null,
// "page_type_reset_pass": null,
// "page_type_checkout": null,
// "page_type_order_history": null,
// "page_type_wishlist": null,
// "page_type_comparsion": null,
// "page_type_search": null,
// "page_type_catalog": null,
// "page_type_news": null,
// "page_type_reviews": null,
// "page_type_live_photos": null,
// "page_type_404": null,
// "page_type_500": null,
// "robots_txt": "",
// "scripts": ""
const siteConfigurationSerializer = (site_configuration) => {
  return {
    ...site_configuration,
    account_slug: site_configuration?.page_type_account,
    login_slug: site_configuration?.page_type_auth,
    cart_slug: site_configuration?.page_type_cart,
    checkout_slug: site_configuration?.page_type_checkout,
    comparision_slug: site_configuration?.page_type_comparsion,
    order_history_slug: site_configuration?.page_type_order_history,
    registration_slug: site_configuration?.page_type_reg,
    reset_pass_slug: site_configuration?.page_type_reset_pass,
    search_slug: site_configuration?.page_type_search,
    wishlist_slug: site_configuration?.page_type_wishlist,
    delivery_condition: site_configuration?.delivery_condition,
    contacts: site_configuration?.contacts,
    //pages
    page_type_cart: site_configuration?.page_type_cart,
    page_type_account: site_configuration?.page_type_account,
    page_type_auth: site_configuration?.page_type_auth,
    page_type_reg: site_configuration?.page_type_reg,
    page_type_reset_pass: site_configuration?.page_type_reset_pass,
    page_type_checkout: site_configuration?.page_type_checkout,
    page_type_order_history: site_configuration?.page_type_order_history,
    page_type_wishlist: site_configuration?.page_type_wishlist,
    page_type_comparsion: site_configuration?.page_type_comparsion,
    page_type_search: site_configuration?.page_type_search,
    page_type_catalog: site_configuration?.page_type_catalog,
    page_type_news: site_configuration?.page_type_news,
    page_type_reviews: site_configuration?.page_type_reviews,
    page_type_live_photos: site_configuration?.page_type_live_photos,
    page_type_404: site_configuration?.page_type_404,
    page_type_500: site_configuration?.page_type_500,
  };
};

export default siteConfigurationSerializer;
